/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModeloGUI;

import EncapsulationObjects.CiudadEncapsulation;

import javax.swing.*;
import java.util.ArrayList;


/**
 *
 * @author DETPC
 */
public class Ciudad extends javax.swing.JFrame {

    DBMethods methods = new DBMethods();

    /**
     * Creates new form CiudadEncapsulation
     */
    public Ciudad() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Set and declare all combo boxes
        ArrayList<String> IDCiudadArray = new ArrayList<>();
        IDCiudadArray = methods.getIDCiudad();
        cmbIDCiudad.setModel(new javax.swing.DefaultComboBoxModel(IDCiudadArray.toArray(new String[0])));

        cmbIDCiudad.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnUpdate.setEnabled(false);


        /*
        ArrayList<String> val;
        val = methods.getIDCiudad();
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(val.toArray(new String[0])));
         */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreCiudad = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtNumHabitantes = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        cmbIDCiudad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDatosCiudad = new javax.swing.JTextArea();
        btnVerDatos = new javax.swing.JButton();
        chkHabilitarEdicion = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmiCerrarVentana5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre ciudad");

        jLabel3.setText("Estado");

        jLabel4.setText("Numero Habitantes");

        txtNombreCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCiudadActionPerformed(evt);
            }
        });

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        txtNumHabitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumHabitantesActionPerformed(evt);
            }
        });

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        cmbIDCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIDCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIDCiudadActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Ciudad");
        jLabel1.setToolTipText("ID Ciudad");

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtAreaDatosCiudad.setColumns(20);
        txtAreaDatosCiudad.setRows(5);
        jScrollPane1.setViewportView(txtAreaDatosCiudad);

        btnVerDatos.setText("Ver Datos");
        btnVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatosActionPerformed(evt);
            }
        });

        chkHabilitarEdicion.setText("Habilitar Actualizar y Eliminar");
        chkHabilitarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHabilitarEdicionActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jmiCerrarVentana5.setText("Cerrar Ciudad");
        jmiCerrarVentana5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCerrarVentana5ActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCerrarVentana5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnInsertar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnUpdate)
                                                .addGap(12, 12, 12)
                                                .addComponent(btnEliminar))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel1))
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cmbIDCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(txtNombreCiudad)
                                                                .addComponent(txtEstado)
                                                                .addComponent(txtNumHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(chkHabilitarEdicion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnVerDatos))
                                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cmbIDCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1))
                                        .addComponent(btnVerDatos, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtNumHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnInsertar)
                                                        .addComponent(btnUpdate)
                                                        .addComponent(btnEliminar))
                                                .addGap(18, 18, 18)
                                                .addComponent(chkHabilitarEdicion)
                                                .addContainerGap(160, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1)
                                                .addContainerGap())))
        );

        pack();
    }// </editor-fold>

    private void jmiCerrarVentana5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCerrarVentana5ActionPerformed
        // TODO add your handling code here:
        MenuFactura obj= new MenuFactura();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiCerrarVentana5ActionPerformed

    private void chkHabilitarEdicionActionPerformed(java.awt.event.ActionEvent evt) {
        if(chkHabilitarEdicion.isSelected()){
            cmbIDCiudad.setEnabled(true);
            btnEliminar.setEnabled(true);
            btnUpdate.setEnabled(true);
        }else{
            cmbIDCiudad.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {
        methods.setCiudad(txtNombreCiudad.getText(), txtEstado.getText(), txtNumHabitantes.getText());
    }

    private void btnVerDatosActionPerformed(java.awt.event.ActionEvent evt) {
        txtAreaDatosCiudad.setText("");
        ArrayList<CiudadEncapsulation> ciudadView = new ArrayList<>();
        ciudadView = methods.ciudadView();
        String viewOfCiudad = "";
        for(CiudadEncapsulation i: ciudadView){
            viewOfCiudad = "[ " + i.id + " " + i.nombreCiudad + " " + i.estado + " " + i.numeroHabitantes + " ]" + "\n";
            txtAreaDatosCiudad.append(viewOfCiudad);
        }

    }
    private void cmbIDCiudadActionPerformed(java.awt.event.ActionEvent evt) {
        /*
         ArrayList<CiudadEncapsulation> data = new ArrayList<CiudadEncapsulation>();
        data = methods.searchRowCiudad(Integer.parseInt( (String) jComboBox1.getSelectedItem()));

        lblExample.setText(data.get(0).estado + " "  + data.get(0).nombreCiudad);
         */
        ArrayList<CiudadEncapsulation> data = new ArrayList<CiudadEncapsulation>();
        data = methods.searchRowCiudad(Integer.parseInt((String) cmbIDCiudad.getSelectedItem()));
        txtNombreCiudad.setText(data.get(0).nombreCiudad);
        txtEstado.setText(data.get(0).estado);
        txtNumHabitantes.setText(data.get(0).numeroHabitantes);
    }

    private void txtNombreCiudadActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNumHabitantesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        methods.updateCiudad(Integer.parseInt((String) cmbIDCiudad.getSelectedItem()), txtNombreCiudad.getText(), txtEstado.getText(), txtNumHabitantes.getText());
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        methods.deleteCiudad(Integer.parseInt((String) cmbIDCiudad.getSelectedItem()));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ciudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ciudad().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVerDatos;
    private javax.swing.JCheckBox chkHabilitarEdicion;
    private javax.swing.JComboBox<String> cmbIDCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiCerrarVentana5;
    private javax.swing.JTextArea txtAreaDatosCiudad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtNumHabitantes;
    // End of variables declaration
}
