/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epn_fact;

import EncapsulationObjects.ProductoEncapsulation;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;
/**
 *
 * @author Adhisson Cedeño
 */
public class CrearFactura extends javax.swing.JPanel {
    
    DBMethods methods = new DBMethods();
    private DefaultTableModel tabla;
    
    final double valorIVA = 0.12;
    
    private double total = 0.0f;
    private double subTotal= 0.0f;
    private double IVA= 0.0f;
    
    private ArrayList<String[]> clientes;
    private ArrayList<String[]> productos;
    JList listaNombres = new JList();
    DefaultListModel modeloLista = new DefaultListModel();

    // Para guarar la lista de productos
    ArrayList<ProductoEncapsulation> producto = new ArrayList<>();
    ArrayList<ProductoEncapsulation> productosStored = new ArrayList<>();
    // Para guardar detalle de productos
    ArrayList<String[]> detalleProducto = new ArrayList<>();
    
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    
    /**
     * Creates new form Principal
     */
    public CrearFactura() {
        initComponents();
        tabla = new DefaultTableModel();
        tabla.addColumn("Cantidad");
        tabla.addColumn("Nombre");
        tabla.addColumn("Precio Unitario");
        tabla.addColumn("Precio Total");
        jTable1.setModel(tabla);
        
        clientes = new ArrayList<>();
        llenar();
        cargarSugerencias();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        pnlProducto = new javax.swing.JPanel();
        Text3 = new javax.swing.JLabel();
        txtnomprod = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text13 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtcodprod = new javax.swing.JTextField();
        Text16 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtprecio = new javax.swing.JTextField();
        Text21 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtcantidad = new javax.swing.JTextField();
        Text22 = new javax.swing.JLabel();
        pnlCliente = new javax.swing.JPanel();
        Text4 = new javax.swing.JLabel();
        txtcodcliente = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Text18 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        txtnomcliente = new javax.swing.JTextField();
        Text19 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        txtcorreo = new javax.swing.JTextField();
        Text20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Text11 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        txtIVA = new javax.swing.JTextField();
        Text12 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        Text14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Crear Factura");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 740, -1));

        btnAgregar.setBackground(new java.awt.Color(18, 90, 173));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarMousePressed(evt);
            }
        });
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar");
        btnAgregar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 30));

        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 205, 140, 30));

        txtSubtotal.setForeground(new java.awt.Color(102, 102, 102));
        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubtotal.setText("Subtotal");
        txtSubtotal.setBorder(null);
        txtSubtotal.setEnabled(false);
        add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 50, 30));

        jSeparator11.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 50, 10));

        pnlProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text3.setText("Producto");
        pnlProducto.add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        txtnomprod.setBackground(new java.awt.Color(242, 242, 242));
        txtnomprod.setForeground(new java.awt.Color(102, 102, 102));
        txtnomprod.setText("Ingrese el nombre del producto");
        txtnomprod.setBorder(null);
        txtnomprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnomprodMousePressed(evt);
            }
        });
        txtnomprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnomprodKeyReleased(evt);
            }
        });
        pnlProducto.add(txtnomprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 170, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlProducto.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, -1));

        Text13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text13.setText("Nombre");
        pnlProducto.add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlProducto.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 70, -1));

        txtcodprod.setBackground(new java.awt.Color(242, 242, 242));
        txtcodprod.setForeground(new java.awt.Color(102, 102, 102));
        txtcodprod.setText("Código");
        txtcodprod.setBorder(null);
        txtcodprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcodprodMousePressed(evt);
            }
        });
        pnlProducto.add(txtcodprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 70, 20));

        Text16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text16.setText("Código");
        pnlProducto.add(Text16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlProducto.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 70, -1));

        txtprecio.setBackground(new java.awt.Color(242, 242, 242));
        txtprecio.setForeground(new java.awt.Color(102, 102, 102));
        txtprecio.setText("Precio");
        txtprecio.setBorder(null);
        txtprecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtprecioMousePressed(evt);
            }
        });
        pnlProducto.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 70, 20));

        Text21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text21.setText("Precio");
        pnlProducto.add(Text21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlProducto.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 70, -1));

        txtcantidad.setBackground(new java.awt.Color(242, 242, 242));
        txtcantidad.setForeground(new java.awt.Color(102, 102, 102));
        txtcantidad.setText("Cantidad");
        txtcantidad.setBorder(null);
        txtcantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcantidadMousePressed(evt);
            }
        });
        pnlProducto.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 70, 20));

        Text22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text22.setText("Cantidad");
        pnlProducto.add(Text22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        add(pnlProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 760, 80));

        pnlCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Text4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text4.setText("Cliente");
        pnlCliente.add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        txtcodcliente.setBackground(new java.awt.Color(242, 242, 242));
        txtcodcliente.setForeground(new java.awt.Color(102, 102, 102));
        txtcodcliente.setText("Ingrese el código del cliente");
        txtcodcliente.setBorder(null);
        txtcodcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcodclienteMousePressed(evt);
            }
        });
        txtcodcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodclienteKeyReleased(evt);
            }
        });
        pnlCliente.add(txtcodcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 150, 20));

        jSeparator12.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlCliente.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, -1));

        Text18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text18.setText("Código");
        pnlCliente.add(Text18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jSeparator17.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator17.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlCliente.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, -1));

        txtnomcliente.setBackground(new java.awt.Color(242, 242, 242));
        txtnomcliente.setForeground(new java.awt.Color(102, 102, 102));
        txtnomcliente.setText("Nombre y Apellido");
        txtnomcliente.setBorder(null);
        txtnomcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnomclienteMousePressed(evt);
            }
        });
        pnlCliente.add(txtnomcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 150, 20));

        Text19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text19.setText("Nombre");
        pnlCliente.add(Text19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jSeparator18.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator18.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlCliente.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 150, -1));

        txtcorreo.setBackground(new java.awt.Color(242, 242, 242));
        txtcorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtcorreo.setText("Correo Electrónico");
        txtcorreo.setBorder(null);
        txtcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcorreoMousePressed(evt);
            }
        });
        pnlCliente.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 150, 20));

        Text20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text20.setText("Correo");
        pnlCliente.add(Text20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        add(pnlCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Nombre", "Precio Unitario", "Precio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 760, 140));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("SubTotal");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 395, -1, -1));

        btnCrear.setBackground(new java.awt.Color(18, 90, 173));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCrearMousePressed(evt);
            }
        });
        btnCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear");
        btnCrear.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 30));

        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 140, 30));

        jSeparator14.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 50, 10));

        txtIVA.setForeground(new java.awt.Color(102, 102, 102));
        txtIVA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIVA.setText("IVA");
        txtIVA.setToolTipText("");
        txtIVA.setBorder(null);
        txtIVA.setEnabled(false);
        add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 50, 30));

        Text12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text12.setText("IVA");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 395, -1, -1));

        jSeparator15.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator15.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 50, 10));

        txtTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setText("Total");
        txtTotal.setBorder(null);
        txtTotal.setEnabled(false);
        add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 50, 30));

        Text14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text14.setText("Total");
        add(Text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 395, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        setColor(btnAgregar);
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        resetColor(btnAgregar);
    }//GEN-LAST:event_btnAgregarMouseExited

    private void txtnomprodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnomprodMousePressed
        resetAll();
        if (txtnomprod.getText().equals("Ingrese el nombre del producto")) {
            txtnomprod.setText("");
        }
    }//GEN-LAST:event_txtnomprodMousePressed

    
    private void btnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMousePressed
        //agrego los productos a mi tabla
        String precioUni = methods.searchRowProducto(Integer.parseInt(txtcodprod.getText())).get(0).precioProducto;
        String precioTot = String.valueOf(Float.parseFloat(precioUni) * Integer.parseInt(txtcantidad.getText()));
        String[] row = {txtcantidad.getText(), txtnomprod.getText(), precioUni, precioTot};
        tabla.addRow(row);
        
        //agrego el producto a una lista para crear los detalles
        producto = methods.searchRowProducto(Integer.parseInt(txtcodprod.getText()));
        productosStored.add(producto.get(0));
        
        //calculo subtotal, iva y total
        subTotal += Double.parseDouble(precioTot);
        IVA = subTotal * valorIVA;
        total = subTotal + IVA;
        
        txtSubtotal.setText(String.valueOf(subTotal));
        txtIVA.setText(String.valueOf(IVA));
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnAgregarMousePressed

    private void txtcodprodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcodprodMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodprodMousePressed

    private void txtcodclienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcodclienteMousePressed
        resetAll();
        if (txtcodcliente.getText().equals("Ingrese el código del cliente")) {
            txtcodcliente.setText("");
        }
    }//GEN-LAST:event_txtcodclienteMousePressed

    private void txtnomclienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnomclienteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomclienteMousePressed

    private void txtcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoMousePressed

    private void txtprecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtprecioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioMousePressed

    private void txtcantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcantidadMousePressed
        // TODO add your handling code here:
        resetAll();
        if (txtcantidad.getText().equals("Cantidad")) {
            txtcantidad.setText("");
        }
    }//GEN-LAST:event_txtcantidadMousePressed

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        setColor(btnCrear);
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        resetColor(btnCrear);
    }//GEN-LAST:event_btnCrearMouseExited

    private void btnCrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMousePressed
        //aquí se tiene que crear una factura
        String fecha = dtf.format(LocalDateTime.now());
        //setFactura(String codCliente, String fechaEmision, String formaPago, 
                    //String totalFactura,String subtotal, String descuento, String iva,String total)
        String numFactura = methods.setFactura(txtcodcliente.getText(), fecha, "Efectivo", String.valueOf(total),
                String.valueOf(subTotal), "1", String.valueOf(IVA), String.valueOf(total));
        JOptionPane.showMessageDialog(this, "¡Factura creada correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        for(int i=0; i<productosStored.size(); i++){
           methods.setDetalleProducto(numFactura,productosStored.get(i).codigoProducto,detalleProducto.get(i)[2], productosStored.get(i).precioProducto, productosStored.get(i).tipoProducto);
        }
    }//GEN-LAST:event_btnCrearMousePressed

    private void txtcodclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodclienteKeyReleased
        //Este método rellenará los campos
        try {
            int codcli = Integer.parseInt(txtcodcliente.getText());
            int aux;
            for (String[] i : clientes) {
                aux = Integer.parseInt(i[0]);
                if (aux == codcli) {
                    txtnomcliente.setText(i[2].replaceAll("\\s", "")+" "+i[3].replaceAll("\\s", ""));
                    txtcorreo.setText(i[4]);
                }
            }
        } catch (NumberFormatException ne) {
            
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_txtcodclienteKeyReleased

    private void txtnomprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomprodKeyReleased
        try {
            String aux1 = txtnomprod.getText().trim();
            for (String[] i : productos) {
                if (aux1.equalsIgnoreCase(i[1].trim())) {
                    txtcodprod.setText(i[0]);
                    txtprecio.setText(i[4]);
                }
            }
        } catch (NumberFormatException ne) {
            
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_txtnomprodKeyReleased

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    private void llenar(){
        //obtengo toda la base de clientes
        clientes = methods.clienteView();
        productos = methods.productoView();
    }

    private void cargarSugerencias(){
        crearLista();
        AutoCompleteDecorator.decorate(listaNombres, txtnomprod, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
    }
    
    private void resetAll(){
        if (txtcodcliente.getText().equals("") || txtcodcliente.getText() == null || txtcodcliente.getText().equals(" ")) {
            txtcodcliente.setText("Ingrese el código del cliente");
        }
        if (txtnomprod.getText().equals("") || txtnomprod.getText() == null || txtnomprod.getText().equals(" ")) {
            txtnomprod.setText("Ingrese el nombre del producto");
        }
        if (txtnomprod.getText().equals("") || txtnomprod.getText() == null || txtnomprod.getText().equals(" ")) {
            txtnomprod.setText("Cantidad");
        }
    }

    private void crearLista(){
        //Este método crea una lista con los nombres de los productos y se la pasamos al método cargar sugerencias.
        //.trim elimina los espacios en blanco del inicio y final
        listaNombres = new JList();
        modeloLista = new DefaultListModel();
        for(String[] i: productos){
            modeloLista.addElement(i[1].trim());
        }
        listaNombres.setModel(modeloLista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text14;
    private javax.swing.JLabel Text16;
    private javax.swing.JLabel Text18;
    private javax.swing.JLabel Text19;
    private javax.swing.JLabel Text20;
    private javax.swing.JLabel Text21;
    private javax.swing.JLabel Text22;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcodcliente;
    private javax.swing.JTextField txtcodprod;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnomcliente;
    private javax.swing.JTextField txtnomprod;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
