package epn_fact;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;

public class Dashboard extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciembre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        Principal p1 = new Principal();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btn_genFactura = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_ing_cliente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_act_cliente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_ver_productos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_act_producto = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_ing_producto = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_ver_ciudades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_act_ciudad = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_ing_ciudad = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_ver_facturas = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_ver_cliente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        app_name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        btn_prin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Title = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_genFactura.setBackground(new java.awt.Color(21, 101, 192));
        btn_genFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_genFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_genFacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_genFacturaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_genFacturaMousePressed(evt);
            }
        });
        btn_genFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_genFactura.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Generar Factura");
        btn_genFactura.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_genFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        btn_ing_cliente.setBackground(new java.awt.Color(18, 90, 173));
        btn_ing_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ing_cliente.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ing_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ing_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ing_clienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ing_clienteMousePressed(evt);
            }
        });
        btn_ing_cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ing_cliente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresar Cliente");
        btn_ing_cliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_ing_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        btn_act_cliente.setBackground(new java.awt.Color(18, 90, 173));
        btn_act_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_act_cliente.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_act_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_act_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_act_clienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_act_clienteMousePressed(evt);
            }
        });
        btn_act_cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_act_cliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actualizar Cliente");
        btn_act_cliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_act_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        btn_ver_productos.setBackground(new java.awt.Color(18, 90, 173));
        btn_ver_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ver_productos.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ver_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ver_productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ver_productosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ver_productosMousePressed(evt);
            }
        });
        btn_ver_productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ver_productos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ver Productos");
        btn_ver_productos.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_ver_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        btn_act_producto.setBackground(new java.awt.Color(18, 90, 173));
        btn_act_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_act_producto.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_act_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_act_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_act_productoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_act_productoMousePressed(evt);
            }
        });
        btn_act_producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_act_producto.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Actualizar Producto");
        btn_act_producto.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_act_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        btn_ing_producto.setBackground(new java.awt.Color(18, 90, 173));
        btn_ing_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ing_producto.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ing_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ing_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ing_productoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ing_productoMousePressed(evt);
            }
        });
        btn_ing_producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ing_producto.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ingresar Producto");
        btn_ing_producto.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_ing_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        btn_ver_ciudades.setBackground(new java.awt.Color(18, 90, 173));
        btn_ver_ciudades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ver_ciudades.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ver_ciudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ver_ciudadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ver_ciudadesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ver_ciudadesMousePressed(evt);
            }
        });
        btn_ver_ciudades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ver_ciudades.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ver Ciudades");
        btn_ver_ciudades.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_ver_ciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        btn_act_ciudad.setBackground(new java.awt.Color(18, 90, 173));
        btn_act_ciudad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_act_ciudad.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_act_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_act_ciudadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_act_ciudadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_act_ciudadMousePressed(evt);
            }
        });
        btn_act_ciudad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_act_ciudad.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Actualizar Ciudad");
        btn_act_ciudad.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_act_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, -1, -1));

        btn_ing_ciudad.setBackground(new java.awt.Color(18, 90, 173));
        btn_ing_ciudad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ing_ciudad.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ing_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ing_ciudadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ing_ciudadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ing_ciudadMousePressed(evt);
            }
        });
        btn_ing_ciudad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ing_ciudad.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ingresar Ciudad");
        btn_ing_ciudad.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_ing_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, -1));

        btn_ver_facturas.setBackground(new java.awt.Color(18, 90, 173));
        btn_ver_facturas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ver_facturas.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ver_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ver_facturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ver_facturasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ver_facturasMousePressed(evt);
            }
        });
        btn_ver_facturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ver_facturas.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ver Facturas");
        btn_ver_facturas.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_ver_facturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        btn_ver_cliente.setBackground(new java.awt.Color(18, 90, 173));
        btn_ver_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ver_cliente.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_ver_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ver_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ver_clienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ver_clienteMousePressed(evt);
            }
        });
        btn_ver_cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ver_cliente.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ver Clientes");
        btn_ver_cliente.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_ver_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setText("Facturas");
        Menu.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 190, 20));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        Header.setBackground(new java.awt.Color(25, 118, 210));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administración/Control/Ventas/Facturas");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 39, -1, 30));

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es Sábado 3 de Abril del 2022");
        Header.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 87, -1, 30));

        btn_prin.setBackground(new java.awt.Color(21, 101, 192));
        btn_prin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_prin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_prinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_prinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_prinMousePressed(evt);
            }
        });
        btn_prin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Principal");
        btn_prin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 30));

        Header.add(btn_prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 30));

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 750, 150));

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleMouseDragged(evt);
            }
        });
        Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleMousePressed(evt);
            }
        });

        red_squr.setBackground(new java.awt.Color(255, 255, 255));
        red_squr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        red_squr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                red_squrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                red_squrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                red_squrMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 102, 102));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addGap(0, 984, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(red_squr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        slogan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slogan.setText("No te olvides de tomar agüita ♥ ");
        Background.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 220, 30));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        Background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 750, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void TitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_TitleMouseDragged

    private void TitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TitleMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void btn_prinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prinMousePressed
        resetAll();
        setColor(btn_prin);

        // Abrir sección
        Principal p1 = new Principal();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_prinMousePressed

    private void btn_ver_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_clienteMousePressed
        resetAll();
        setColor(btn_ver_cliente);

        // Abrir sección
        VerClientes p1 = new VerClientes();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_ver_clienteMousePressed

    private void btn_ing_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_clienteMousePressed
        resetAll();
        setColor(btn_ing_cliente);
        // Abrir sección
        RegistroCliente p1 = new RegistroCliente();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_ing_clienteMousePressed

    private void btn_act_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_clienteMousePressed
        resetAll();
        setColor(btn_act_cliente);
        // Abrir sección
        ActualizarCliente p1 = new ActualizarCliente();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_act_clienteMousePressed

    private void btn_ver_ciudadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_ciudadesMousePressed
        resetAll();
        setColor(btn_ver_ciudades);
        // Abrir sección
        VerCiudades p1 = new VerCiudades();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_ver_ciudadesMousePressed

    private void btn_ing_ciudadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_ciudadMousePressed
        resetAll();
        setColor(btn_ing_ciudad);
        // Abrir sección
        RegistroCiudad p1 = new RegistroCiudad();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_ing_ciudadMousePressed

    private void btn_act_ciudadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_ciudadMousePressed
        resetAll();
        setColor(btn_act_ciudad);
        // Abrir sección
        ActualizarCiudad p1 = new ActualizarCiudad();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_act_ciudadMousePressed

    private void btn_ver_productosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_productosMousePressed
        resetAll();
        setColor(btn_ver_productos);
        // Abrir sección
        VerProductos p1 = new VerProductos();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_ver_productosMousePressed

    private void btn_act_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_productoMousePressed
        resetAll();
        setColor(btn_act_producto);
        // Abrir sección
        ActualizarProducto p1 = new ActualizarProducto();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_act_productoMousePressed

    private void btn_ing_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_productoMousePressed
        resetAll();
        setColor(btn_ing_producto);
        // Abrir sección
        RegistroProducto p1 = new RegistroProducto();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_ing_productoMousePressed


    private void red_squrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMousePressed
        System.exit(0);
    }//GEN-LAST:event_red_squrMousePressed

    private void btn_ver_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_clienteMouseEntered
        setColor(btn_ver_cliente);
    }//GEN-LAST:event_btn_ver_clienteMouseEntered

    private void btn_ver_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_clienteMouseExited
        resetAll();
    }//GEN-LAST:event_btn_ver_clienteMouseExited

    private void btn_prinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prinMouseEntered
        setColor(btn_prin);
    }//GEN-LAST:event_btn_prinMouseEntered

    private void btn_prinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prinMouseExited
        resetAll();
    }//GEN-LAST:event_btn_prinMouseExited

    private void btn_ing_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_clienteMouseEntered
        setColor(btn_ing_cliente);
    }//GEN-LAST:event_btn_ing_clienteMouseEntered

    private void btn_ing_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_clienteMouseExited
        resetAll();
    }//GEN-LAST:event_btn_ing_clienteMouseExited

    private void btn_act_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_clienteMouseEntered
        setColor(btn_act_cliente);
    }//GEN-LAST:event_btn_act_clienteMouseEntered

    private void btn_act_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_clienteMouseExited
        resetAll();
    }//GEN-LAST:event_btn_act_clienteMouseExited

    private void btn_ver_ciudadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_ciudadesMouseEntered
        setColor(btn_ver_ciudades);
    }//GEN-LAST:event_btn_ver_ciudadesMouseEntered

    private void btn_ver_ciudadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_ciudadesMouseExited
        resetAll();
    }//GEN-LAST:event_btn_ver_ciudadesMouseExited

    private void btn_ing_ciudadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_ciudadMouseEntered
        setColor(btn_ing_ciudad);
    }//GEN-LAST:event_btn_ing_ciudadMouseEntered

    private void btn_ing_ciudadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_ciudadMouseExited
        resetAll();
    }//GEN-LAST:event_btn_ing_ciudadMouseExited

    private void btn_act_ciudadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_ciudadMouseEntered
        setColor(btn_act_ciudad);
    }//GEN-LAST:event_btn_act_ciudadMouseEntered

    private void btn_act_ciudadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_ciudadMouseExited
        resetAll();
    }//GEN-LAST:event_btn_act_ciudadMouseExited

    private void btn_ver_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_productosMouseEntered
        setColor(btn_ver_productos);
    }//GEN-LAST:event_btn_ver_productosMouseEntered

    private void btn_ver_productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_productosMouseExited
        resetAll();
    }//GEN-LAST:event_btn_ver_productosMouseExited

    private void btn_ing_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_productoMouseEntered
        setColor(btn_ing_producto);
    }//GEN-LAST:event_btn_ing_productoMouseEntered

    private void btn_ing_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ing_productoMouseExited
        resetAll();
    }//GEN-LAST:event_btn_ing_productoMouseExited

    private void btn_act_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_productoMouseEntered
        setColor(btn_act_producto);
    }//GEN-LAST:event_btn_act_productoMouseEntered

    private void btn_act_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_act_productoMouseExited
        resetAll();
    }//GEN-LAST:event_btn_act_productoMouseExited

    private void red_squrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseEntered

    private void red_squrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_red_squrMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_exitMouseExited

    private void btn_genFacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_genFacturaMouseEntered
        setColor(btn_genFactura);
    }//GEN-LAST:event_btn_genFacturaMouseEntered

    private void btn_genFacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_genFacturaMouseExited
        resetAll();
    }//GEN-LAST:event_btn_genFacturaMouseExited

    private void btn_genFacturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_genFacturaMousePressed
        resetAll();
        setColor(btn_genFactura);
        // Abrir sección
        CrearFactura p1 = new CrearFactura();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_genFacturaMousePressed

    private void btn_ver_facturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_facturasMouseEntered
        setColor(btn_ver_facturas);
    }//GEN-LAST:event_btn_ver_facturasMouseEntered

    private void btn_ver_facturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_facturasMouseExited
        resetColor(btn_ver_facturas);
    }//GEN-LAST:event_btn_ver_facturasMouseExited

    private void btn_ver_facturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ver_facturasMousePressed
        resetAll();
        setColor(btn_genFactura);
        // Abrir sección
        VerFacturas p1 = new VerFacturas();
        p1.setSize(750, 430);
        p1.setLocation(0, 0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_ver_facturasMousePressed


    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    void resetAll(){
        resetColor(btn_prin);
        resetColor(btn_ver_facturas);
        resetColor(btn_genFactura);
        
        resetColor(btn_ver_cliente);
        resetColor(btn_ing_cliente);
        resetColor(btn_act_cliente);
        
        resetColor(btn_ver_productos);
        resetColor(btn_ing_producto);
        resetColor(btn_act_producto);
        
        resetColor(btn_ver_ciudades);
        resetColor(btn_ing_ciudad);
        resetColor(btn_act_ciudad);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Title;
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel btn_act_ciudad;
    private javax.swing.JPanel btn_act_cliente;
    private javax.swing.JPanel btn_act_producto;
    private javax.swing.JPanel btn_genFactura;
    private javax.swing.JPanel btn_ing_ciudad;
    private javax.swing.JPanel btn_ing_cliente;
    private javax.swing.JPanel btn_ing_producto;
    private javax.swing.JPanel btn_prin;
    private javax.swing.JPanel btn_ver_ciudades;
    private javax.swing.JPanel btn_ver_cliente;
    private javax.swing.JPanel btn_ver_facturas;
    private javax.swing.JPanel btn_ver_productos;
    public static javax.swing.JPanel content;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel red_squr;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}