/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epn_fact;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;

/**
 *
 * @author Adhisson Cedeño
 */
public class VerFacturas extends javax.swing.JPanel {
    DBMethods methods = new DBMethods();
    DefaultTableModel dtmFactura;
    DefaultTableModel dtmDetalles;
    
    JList listaNombres = new JList();
    DefaultListModel modeloLista = new DefaultListModel();
    
    private ArrayList<String[]> clientes;

    /**
     * Creates new form Principal
     */
    public VerFacturas() {
        initComponents();
        dtmFactura = new DefaultTableModel();
        dtmFactura.addColumn("Número");
        dtmFactura.addColumn("Código del Cliente");
        dtmFactura.addColumn("Fecha");
        dtmFactura.addColumn("Forma de Pago");
        dtmFactura.addColumn("SubTotal");
        dtmFactura.addColumn("IVA");
        dtmFactura.addColumn("Total");
        tblFacturas.setModel(dtmFactura);
        
        dtmDetalles = new DefaultTableModel();
        dtmDetalles.addColumn("Número de Detalle");
        dtmDetalles.addColumn("Número de Factura");
        dtmDetalles.addColumn("Código del Producto");
        dtmDetalles.addColumn("Cantidad de Unidades");
        dtmDetalles.addColumn("Precio de Venta");
        dtmDetalles.addColumn("Categoría");
        tblDetalles.setModel(dtmDetalles);
            
        try {
            getFacturas();
        } catch (Exception ex) { }
        llenar();
        cargarSugerencias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        Title1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtFechaInicio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtFechaFin = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Detalles de la Factura");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 10));

        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("Ingrese el nombre de la persona a buscar");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 30));

        btnBuscar.setBackground(new java.awt.Color(18, 90, 173));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Buscar");
        btnBuscar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 80, 30));

        tblDetalles.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número de Detalle", "Número de Factura", "Código del Producto", "Cantidad de Unidades", "Precio de Venta", "Categoría"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalles.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDetalles);
        if (tblDetalles.getColumnModel().getColumnCount() > 0) {
            tblDetalles.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 750, 120));

        tblFacturas.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Código del Cliente", "Fecha", "Forma de Pago", "SubTotal", "IVA", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFacturas.getTableHeader().setReorderingAllowed(false);
        tblFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFacturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFacturas);
        if (tblFacturas.getColumnModel().getColumnCount() > 0) {
            tblFacturas.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 750, 170));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("Facturas");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 110, 10));

        txtFechaInicio.setForeground(new java.awt.Color(102, 102, 102));
        txtFechaInicio.setText("Fecha de Inicio");
        txtFechaInicio.setBorder(null);
        txtFechaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaInicioMousePressed(evt);
            }
        });
        add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 110, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 110, 10));

        txtFechaFin.setForeground(new java.awt.Color(102, 102, 102));
        txtFechaFin.setText("Fecha de Fin");
        txtFechaFin.setBorder(null);
        txtFechaFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaFinMousePressed(evt);
            }
        });
        add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        resetAll();
        if (txtNombre.getText().equals("Ingrese el nombre de la persona a buscar")) {
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        setColor(btnBuscar);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        resetColor(btnBuscar);
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed
        //Buscar por nombre
        if (!txtNombre.getText().equals("Ingrese el nombre de la persona a buscar")
                && !txtNombre.getText().equals("") && txtNombre.getText() != null) {
            dtmFactura.setRowCount(0);
            String nomAux;
            ArrayList<String[]> facturaFilterClienteView = new ArrayList<>();
            for (String[] i : clientes) {
                nomAux = i[2].trim() + " " + i[3].trim();
                if (txtNombre.getText().equals(nomAux)) {
                    facturaFilterClienteView = methods.facturaFilterClienteView(i[0]);
                }
            }
            for (String[] i : facturaFilterClienteView) {
                dtmFactura.addRow(new Object[]{i[0],i[1],i[2],i[3],i[7],i[6],i[8]});
            }
            return;
        }
        
        //Buscar entre fechas
        if (!txtFechaInicio.getText().equals("Fecha de Inicio") && !txtFechaFin.getText().equals("Fecha de Fin")
                && !txtFechaInicio.getText().equals("") && txtFechaInicio.getText() != null
                && !txtFechaFin.getText().equals("") && txtFechaFin.getText() != null) {
            
            dtmFactura.setRowCount(0);
            ArrayList<String[]> viewFactura = new ArrayList<>();
            viewFactura = methods.facturaFilterFechaView(txtFechaInicio.getText(), txtFechaFin.getText());

            for (String[] i : viewFactura) {
                dtmFactura.addRow(new Object[]{i[0],i[1],i[2],i[3],i[7],i[6],i[8]});
            }
        }
    }//GEN-LAST:event_btnBuscarMousePressed

    private void txtFechaInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaInicioMousePressed
        resetAll();
        if (txtFechaInicio.getText().equals("Fecha de Inicio")) {
            txtFechaInicio.setText("");
        }
    }//GEN-LAST:event_txtFechaInicioMousePressed

    private void txtFechaFinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaFinMousePressed
        resetAll();
        if (txtFechaFin.getText().equals("Fecha de Fin")) {
            txtFechaFin.setText("");
        }
    }//GEN-LAST:event_txtFechaFinMousePressed

    private void tblFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFacturasMouseClicked
        String selectedFactura = "";
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());
        selectedFactura = source.getModel().getValueAt(row ,column) + "" ;

        dtmDetalles.setRowCount(0);
        ArrayList<String[]> selectedDetalle = new ArrayList<>();
        selectedDetalle = methods.detalleFacturaView(selectedFactura);
        for(String[] i : selectedDetalle){
            dtmDetalles.addRow(i);
        }
    }//GEN-LAST:event_tblFacturasMouseClicked

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    private void getFacturas() throws SQLException{
        dtmFactura.setRowCount(0);
        ArrayList<String[]> viewFacturas = new ArrayList<>();
        viewFacturas = methods.facturaView();
        for(String[] i : viewFacturas){
            dtmFactura.addRow(new Object[]{i[0],i[1],i[2],i[3],i[7],i[6],i[8]});
        }
    }
    
    private void cargarSugerencias(){
        crearLista();
        AutoCompleteDecorator.decorate(listaNombres, txtNombre, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
    }
    
    private void crearLista(){
        //.trim elimina los espacios en blanco del inicio y final
        listaNombres = new JList();
        modeloLista = new DefaultListModel();
        String nomAux = "";
        for(String[] i: clientes){
            nomAux = i[2].trim() + " " +i[3].trim();
            modeloLista.addElement(nomAux);
        }
        listaNombres.setModel(modeloLista);
    }
    
    private void llenar(){
        //obtengo toda la base de clientes
        clientes = methods.clienteView();
    }
    
    private void resetAll(){
        if (txtNombre.getText().equals("") || txtNombre.getText() == null || txtNombre.getText().equals(" ")) {
            txtNombre.setText("Ingrese el nombre de la persona a buscar");
        }
        if (txtFechaInicio.getText().equals("") || txtFechaInicio.getText() == null || txtFechaInicio.getText().equals(" ")) {
            txtFechaInicio.setText("Fecha de Inicio");
        }
        if (txtFechaFin.getText().equals("") || txtFechaFin.getText() == null || txtFechaFin.getText().equals(" ")) {
            txtFechaFin.setText("Fecha de Fin");
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
